### ISSUE TITLE
[WebToolsE2E][Aspire] After adding the "Aspire.Microsoft.Azure.Cosmos" component and updating the relevant code, I get an error: "'IDistributedApplicationBuilder' does not contain a definition for 'AddAzureCosmosDB'"...

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/aspire#1098]
**REGRESSION INFO**: Also repro on 17.9 Preview 1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 Preview 2 from [34328.156.main]
3. CLI workload update and install aspire
4. Apply NuGet Feeds

**REPRO STEPS**

1. In the VS, create a new project > ASP.NET Core Web App(Razor Page) > .NET 8.0 > check 'Enlist in Aspire Orchestration' > Create
2. Right-click the Razor project > Add > .NET Aspire Component > set Paclkage source to 'All' and check 'Include prerelease' > then install the latest 'Aspire.Microsoft.Azure.Cosmos' component 
3. Open appsettings.json file under Razor project, type following codes:
```
	{
	  "Aspire": {
	    "Microsoft": {
	      "Azure": {
	        "Cosmos": {
	          "Tracing": true,
	        }
	      }
	    }
	  }
}
```
4. Open Program.cs file under Razor project, type following codes:
`builder.AddAzureCosmosDB("cosmosConnectionName");`
5. In the appsettings.json of xxx.AppHost project, type following codes:
```
	{
	  "ConnectionStrings": {
	    "cosmosConnectionName": "https://{account_name}.documents.azure.com:443/"
	  }
}
```
6. Open Program.cs of xxx.AppHost project, type following codes:
```
	var cosmosdb = builder.AddAzureCosmosDB("cdb").AddDatabase("cosmosdb");
	 
	var myService = builder.AddProject<Projects.MyService>()
                       .WithReference(cosmosdb);
```

**ACTUAL**
Error CS1061 'IDistributedApplicationBuilder' does not contain a definition for 'AddAzureCosmosDB' and no accessible extension method 'AddAzureCosmosDB' accepting a first argument of type 'IDistributedApplicationBuilder' could be found (are you missing a using directive or an assembly reference?)
![image](https://github.com/dotnet/aspire/assets/71361488/fd95d8ef-8d39-46e9-9541-5e5b4bd89900)

**EXPECTED**

No errors shown

**Comment by fleccy** [comment]
Try adding the nuget package "Aspire.Hosting.Azure". This should resolve the issue.

**Comment by DamianEdwards** [comment]
TBC, the package `Aspire.Hosting.Azure` must be added to the AppHost project in order to use the `AddAzureCosmos` method there.

We have some early thoughts about how to improve the experience when using component packages in service projects and hosting packages in the AppHost project so that keeping both in "sync" is easier.

**Comment by v-sherryfan** [comment]
@fleccy @DamianEdwards After trying to add the nuget package "Aspire.Hosting.Azure" to the AppHost project, still showing other similar error as below.

![image](https://github.com/dotnet/aspire/assets/71361488/006bd257-7d19-4eef-bdbe-6436b5605ff4)
![image](https://github.com/dotnet/aspire/assets/71361488/16372bf8-130c-4121-8b97-6a46b4963294)

**Comment by DamianEdwards** [comment]
Yeah it doesn't seem like there's an `AddDatabase` method for CosmosDB resources. @Pilchie how is this supposed to work? The README for the CosmosDB component shows the above code but I can't see the method declared anywhere in source.

**Comment by davidfowl** [comment]
@mitchdenny this was removed last minute right? We should fix the docs or the API or both 😄

**Comment by peteraritchie** [comment]
What was removed? What can I do to help with this?

**Comment by mitchdenny** [comment]
The `AddDatabase(...)` method doesn't exist for Cosmos DB resource anymore: https://github.com/dotnet/docs-aspire/issues/154

**Comment by mitchdenny** [comment]
https://github.com/dotnet/docs-aspire/pull/155

**Comment by mitchdenny** [comment]
AddDatabase method was added back in.

**Comment by v-sherryfan** [comment]
This issue does not repro on 17.10.0 Preview 1.0 [34509.254.main] + Aspire template 8.0.0-preview.3.24060.9
