### ISSUE TITLE
Support for Custom Hostnames in Local Development

### ISSUE THREAD

**Issue by dotnetian** [dotnet/aspire#1116]
Hello,

I've been using .NET Aspire for developing microservices and it's been a great experience. However, I've encountered a limitation that I believe could be addressed to improve the development experience.

Currently, .NET Aspire uses localhost with different ports for each service during local development. This works well for most scenarios, but there are cases where having a custom hostname for a service would be beneficial. For example, when testing services that rely on absolute URLs or when simulating a production-like environment locally.

I propose adding support for custom hostnames during local development. This could potentially be configured through the `WithServiceBinding` method when adding a project to the builder, like this:

```csharp
var basket = builder.AddProject<Projects.BasketService>("basket")
    .WithServiceBinding(hostPort: 8888, scheme: "http", name: "dashboard", hostName: "bargeh.testdev");
```

I understand that this feature might require significant changes and could have implications on how services are discovered and communicated during development. However, I believe that the flexibility it provides would be a valuable addition to .NET Aspire.

Thank you for considering this feature request.

**Comment by davidfowl** [comment]
> For example, when testing services that rely on absolute URLs or when simulating a production-like environment locally.

Can you elaborate? 

Host name support is non trivial to do without containers and projects don't run in containers by default so I'm not 100% sure what scenarios you are trying to accomplish.

**Comment by dotnetian** [comment]
> Modifying the HOSTS file is a privileged action and not something that a toolchain like .NET Aspire should reasonably do as an automatic part of the dev inner loop in my opinion. Or are you saying that even if you modify the HOSTS file manually, you can't use those URLs in service projects if they're launched via an AppHost project?

I'm issuing that the AppHost cannot make projects' endpoints listen to anything other than `localhost` like this:

```csharp
var smsApi = builder.AddProject<Projects.Bargeh_SMS_API> ("smsapi").WithServiceBinding(hostBase: "bargeh.net");
```

Also, another workaround for this problem is just adding an option so the AppHost reads the `launchSettings.json` file for each project, and hosts them respecting to those, similiar to this:

```csharp
var smsApi = builder.AddProject<Projects.Bargeh_SMS_API> ("smsapi").WithServiceBinding (launchProfile: "https"));
```

**Comment by karolz-ms** [comment]
@dotnetian sorry, I am not sure I fully understand the ask. 

With Aspire preview 1, when you call `AddProject()`, you do give it a "logical name". For example, this is how Catalog service gets its logical name in the Aspire eShopLite sample: https://github.com/dotnet/aspire-samples/blob/main/samples/eShopLite/eShopLite.AppHost/Program.cs#L6

The project/service can then be referred by that name from clients: https://github.com/dotnet/aspire-samples/blob/main/samples/eShopLite/eShopLite.Frontend/Program.cs#L12C60-L12C60

The idea being here, that in your local development environment that name resolves to a combination of local loopback address and some port, but in production environments like Azure Container Apps or Kubernetes, the same logical name will resolve to real container/service IP.  

So could you please elaborate what is it that is missing for you from what Aspire provides already with regards to logical host names. Thanks!

**Comment by DamianEdwards** [comment]
The request is for support of non-localhost host names for endpoints, not the logical names.

**Comment by davidfowl** [comment]
The only valid thing to bind is localhost, *, 0.0.0.0 or the machine IP. Not a host name.

**Comment by DamianEdwards** [comment]
Yeah, binding to localhost or 127.0.0.1, and then editing your HOSTS file to map your custom domain to 127.0.0.1 should work from a networking point of view, but the configuration of service discovery to map your app's references to "http://mycustomdomain.com" would not be automatic. I imagine you could write some hosting extensions to make that work though, by separating the configuration of the endpoint binding and service discovery environment variable values.

**Comment by dotnetian** [comment]
Fixed this issue by setting the launch profile:

```csharp
builder.AddProject<Projects.Bargeh_Main_Wapp> ("bargehmainwapp")
    .WithReference (usersApi)
    .WithReference (smsApi)
    .WithLaunchProfile ("https");
```

**Comment by ryno1234** [comment]
> Fixed this issue by setting the launch profile:
> 
> ```cs
> builder.AddProject<Projects.Bargeh_Main_Wapp> ("bargehmainwapp")
>     .WithReference (usersApi)
>     .WithReference (smsApi)
>     .WithLaunchProfile ("https");
> ```

Not sure how this fixed your problem. I'm trying to do the same thing you are, but this doesn't fix the issue. Apire dashboard is still showing my URL for my project being mapped to localhost:port despite my launchsettings.json for my project having a custom domain.

To the team here, a concrete reason for a custom domain is an application that opperates as Software as a Service with client-specific URLs. Each client gets their own URL, i.e. client1.myapp.com. On my machine, I have custom host entries in the form of client1.myapp.local which maps to 127.0.0.1. The host name is read within the app and we serve up content specific to Client 1. I could easily change this to client2.myapp.local and get a totally different set of content.

Is this not possible right now?

**Comment by davidfowl** [comment]
We should break down the problem encountered. To make host name mappings work in the browser (and every client that relies on the OS for DNS resolution), you have to add host entries on your machine (/etc/hosts on linux and in the appropriate location on windows), this is something you have to do manually. Aspire does not help here (nor does it have plans to help here). You can also use a tool like [dnsmaq](https://github.com/dotnet/aspire/issues/1116#issuecomment-1853926916) to make wildcard routing easier for local dev.

The next piece of the puzzle is port mapping. Aspire is avoiding port conflicts on your local machine by randomly selecting ports. Using an address like `https://client1.myapp.local/` assumes that you have a server listening on :443 (and probably :80) routing requests to the appropriate application.

The last piece of the puzzle is how [aspire's networking](https://github.com/dotnet/docs-aspire/issues/232) interacts with this.

Once you have this, it should be possible to make the end-to-end work.

**Comment by jakenuts** [comment]
I've yet to try, but would an alternate setup where each .local domain is given its own 127.0.0.N ip address help or hinder this setup? Prior to Aspire that was the only way for me to have two related web apps running in Kestrel/IIS Express without clashing over the 80/443 ports.

**Comment by davidfowl** [comment]
I just did it so I know it works 😄. Like I said, Aspire doesn't help you with the fact that you need a proxy on 80/443 that can do subdomain routing. You can use the proxy of your choice (like YARP, nginx, etc) to do that.

**Comment by davidfowl** [comment]
Yes agreed, we could attempt to make this easier, but it's not currently on the roadmap.

**Comment by jakenuts** [comment]
Thanks, this was the configuration I used to get that to work on my system (each local domain has it's own IP address, local wildcard ssl cert).

![image](https://github.com/dotnet/aspire/assets/344606/659886aa-b381-458f-b21e-db0ec19d5b79)

![image](https://github.com/dotnet/aspire/assets/344606/83f13c02-16de-4619-856e-8501481a2273)
