### ISSUE TITLE
Dashboard hangs when shutting down 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspire#1557]
This is what happens when running eshoplite and shutting down.

```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'WatchResourceConsoleLogs'.
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.CancellationToken.ThrowOperationCanceledException()
         at System.Threading.CancellationToken.ThrowIfCancellationRequested()
         at Grpc.AspNetCore.Server.Internal.HttpContextStreamWriter`1.WriteCoreAsync(TResponse message, CancellationToken cancellationToken)
         at Aspire.Hosting.Dashboard.DashboardService.WatchResourceConsoleLogs(WatchResourceConsoleLogsRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\dev\git\aspire\src\Aspire.Hosting\Dashboard\DashboardService.cs:line 110
         at Aspire.Hosting.Dashboard.DashboardService.WatchResourceConsoleLogs(WatchResourceConsoleLogsRequest request, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\dev\git\aspire\src\Aspire.Hosting\Dashboard\DashboardService.cs:line 101
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

**Comment by JamesNK** [comment]
This might be fixed by https://github.com/dotnet/aspire/pull/1578.

**Comment by JamesNK** [comment]
@davidfowl What is the start of the app when you start shutting down? Do you still have a browser open for the dashboard?

**Comment by drewnoakes** [comment]
Fixed in #1589. Note that the fix allows the server to shut down, but there's still a timeout period before things clean up. That timeout exists with #1578 too.

Once the dashboard and app host are separate, the dashboard process shouldn't be keeping the app host alive. I would expect we can avoid that timeout.

**Comment by drewnoakes** [comment]
The error message in the issue description is unrelated to the hang, but is fixed in #1590.

**Comment by davidfowl** [comment]
This isn't fixed, it took 30 seconds to shutdown the dashboard:

<img width="867" alt="image" src="https://github.com/dotnet/aspire/assets/95136/effc4a9b-b08d-4783-9c7d-c96302889212">

Something isn't responding to the shutdown token and unwinding. It's likely the streaming grpc call.

**Comment by JamesNK** [comment]
Are you shutting down while the Aspire dashboard is open?

**Comment by JamesNK** [comment]
[IHostApplicationLifetime](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostapplicationlifetime?view=dotnet-plat-ext-8.0). But I want to understand more about what is happening here. And splitting the app host and dashboard might impact what we do.

@davidfowl Please give more details about what is happening and what do you expect to happen.

In the original issue you said the app hangs on shutdown down. I'm presuming you mean that the app would wait for 30 seconds while trying to drain remaining requests, and then give up and do an abortive shutdown. That's what I observed.

The cancellation fixes that we've added means that the streaming gRPC call is canceled when someone closes the dashboard. If the dashboard UI isn't open the shutting down the app is instant.

However, if someone still has the dashboard UI open, there is still a delay while outstanding HTTP requests are completed. That would include any gRPC calls, but I'm guessing the Blazor Server web socket connection that the browser has open is also included.

When someone CTRL+C's the aspire console and the dashboard UI is open, what do you want to happen?

**Comment by davidfowl** [comment]
I would expect it to not hang for the 30 seconds before shutting down. I recall there being times when this happened but compare it to preview 2 and you’ll see the difference

**Comment by drewnoakes** [comment]
The timing does suggest gRPC connections are involved. I'll pick this up and get a fix filed.

**Comment by drewnoakes** [comment]
Fixed in https://github.com/dotnet/aspire/pull/1633

**Comment by drewnoakes** [comment]
@davidfowl this should be fixed now. Let me know if you see any more delays.
