### ISSUE TITLE
Container app fail to start. Error: No frameworks were found.

### ISSUE THREAD

**Issue by emerbrito** [dotnet/aspire#1737]
Using Visual Studio 2002 17.9.0 Preview 3.0
Aspire Preview 2

I created an aspire app which runs fine locally.
I used `azd up` to deploy it. The command line indicated a successful deployment.
In the Azure portal however the Container App status is failed. It can't initialize it.
Looking into the console log I get this:

    2024-01-19T21:02:52.61183  Successfully Connected to container: 'account-manager' [Revision: 'account-manager--15zqi0t-5f674bc8df-pssz9', Replica: 'account-manager--15zqi0t']
    2024-01-19T21:02:40.877613544Z You must install or update .NET to run this application.
    2024-01-19T21:02:40.877634744Z 
    2024-01-19T21:02:40.877638130Z App: /app/PracticePro.Services.AccountManager.dll
    2024-01-19T21:02:40.877640515Z Architecture: x64
    2024-01-19T21:02:40.877642659Z Framework: 'Microsoft.AspNetCore.App', version '8.0.0' (x64)
    2024-01-19T21:02:40.877644652Z .NET location: /usr/share/dotnet/
    2024-01-19T21:02:40.877646406Z 
    2024-01-19T21:02:40.877648289Z No frameworks were found.
    2024-01-19T21:02:40.877650033Z 
    2024-01-19T21:02:40.877651886Z Learn more:
    2024-01-19T21:02:40.877653840Z https://aka.ms/dotnet/app-launch-failed
    2024-01-19T21:02:40.877655583Z 
    2024-01-19T21:02:40.877657456Z To install missing framework, download:
    2024-01-19T21:02:40.877659540Z https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=8.0.0&arch=x64&rid=linux-x64&os=debian.12

The app was a bit complex so I decided to create a very simple project with all defaults and I got the exact same error.

Here is what I did (steps to reproduce):

- I Started Visual Studio
- Create new project and selected .NET Aspire Application.
- Add a web API project into the the newly created solution, which is automatically registered in the AppHost project (the web api project will have the default Weather forecast controller)
- Run locally to verify it works
- Deploy with `azd init` and `azd up`

The interesting thing is that I can almost swear I did the exact same test with the default apps before I started experimenting with Aspire  (on Preview 2) and it worked.

What am I missing here?

**Comment by davidfowl** [comment]
Can you run `dotnet --info`?

**Comment by emerbrito** [comment]
Sure, here is what I got (and thanks for the prompt response by the way):

.NET SDK:
 Version:           8.0.200-preview.23624.5
 Commit:            8065b9770c
 Workload version:  8.0.200-manifests.ba313bcd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200-preview.23624.5\

.NET workloads installed:
 Workload version: 8.0.200-manifests.ba313bcd
 [maccatalyst]
   Installation Source: VS 17.9.34511.98, VS 17.8.34330.188
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.9.34511.98, VS 17.8.34330.188
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.9.34511.98, VS 17.8.34330.188
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.9.34511.98, VS 17.8.34330.188
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.9.34511.98
   Manifest Version:    8.0.0-preview.2.23619.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.2.23619.3\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]
  8.0.200-preview.23624.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by cfarrugia** [comment]
I'm having this problem as well. I've updated Visual Studio yesterday, but not sure this has anything to do with that (as I haven't tried deploying before that). Am I right in saying that Azure Container Apps come with SDK 8.0.0, but the app is expecting the 8.0.200-preview.23624.5?

**Comment by mip1983** [comment]
Yea, I'm also getting this

**Comment by baronfel** [comment]
Hey folks - this was a regression in the preview 8.0.200 SDKs that we caught and fixed last week in [this PR](https://github.com/dotnet/sdk/pull/37996). By now this has flowed to newer preview SDKs, so if you are using the table on the dotnet/installer repo to get those I'd suggest you grab a newer one. Alternatively, you can do as @mip1983 has done and pin to 8.0.1xx in the meantime.  Very sorry for the mix-up here, but we should be covered from regression going forward.

**Comment by pedershk** [comment]
> @baronfel my guess is folks here are getting the 8.0.200 SDK builds from the VS 17.9 preview they have installed. Any word when the fixed SDK will flow there?

Can confirm this - the latest VS 17.9 preview installs the version of the SDK with the bug still active.

**Comment by davidfowl** [comment]
This should be fixed now with the 8.0.200 SDK.

**Comment by g-martin772** [comment]
I am using the 9.0.0-preview.1.24081.5 version and I am facing the same issue. Adding something like the snipped below to my global.json didn't fix the issue for me. 

```json
{
  "sdk": {
    "version": "9.0.0.1.24081.5"
  }
}
```

![image](https://github.com/dotnet/aspire/assets/95913933/b4800f73-921b-478c-b2ed-926e573536b0)

**Comment by davidfowl** [comment]
This issue was opened in January. It's likely an issue with container builds and preview versions of .NET. I'm closing this as its likely unrelated to aspire.
