### ISSUE TITLE
Adding two wasm projects to the orchestration gives "conflicting assets with the same target path" issue when using aspire. 

### ISSUE THREAD

**Issue by SalomonHenke** [dotnet/aspire#2084]
![image](https://github.com/dotnet/aspire/assets/96744651/d8ffc861-459e-404c-bd39-2efc1a6e3477)
![image](https://github.com/dotnet/aspire/assets/96744651/0cb0cc60-559d-4566-a92a-16b24da00756)

Replicated the issue in the repo. All you have to do is add two standalone wasm projects and enlist them in the orchestration and start the AppHost.

**Comment by radical** [comment]
Did you add two blazorwasm projects? I wasn't able to reproduce this locally, but maybe I missed something. Could you please share a test solution for this?

**Comment by SalomonHenke** [comment]
certainly @radical. Here it is. https://github.com/SalomonHenke/SharingWasm

sidenote: when adding and checking "add to aspire orchestration", it doesnt add it to the projects. I manually configure a dependency from the apphost to the two wasm standalone projects.

**Comment by davidfowl** [comment]
This should be fixed in preview3.

**Comment by danmoseley** [comment]
@SalomonHenke I will close, please reopen  if it's not fixed for you.

**Comment by SalomonHenke** [comment]
Not fixed @danmoseley might be different? adding a standalone wasm gives me this error. 
![image](https://github.com/dotnet/aspire/assets/96744651/01bc5334-d6c5-4a0d-b8ee-08f22934b37b)
