### ISSUE TITLE
gRPC client doesn't work with Service Discovery scheme resolution syntax

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/aspire#2896]
The format used to support URI scheme resolution recently added to service discovery (e.g. `https+http`) does not work with the gRPC client stack. The [`GrpcChannel` class](https://github.com/grpc/grpc-dotnet/blob/933023b6f818ec54dfe84e7d31ec50dfe5044c13/src/Grpc.Net.Client/GrpcChannel.cs#L105) does a lot of initialization in its constructor based on the scheme of the address and special-cases `https://` and `http://` for numerous operations including `ResolverFactory` resolution and credential selection.

**Comment by JamesNK** [comment]
HttpClient happily sends HTTP requests to different hosts over https or http, and you can completely change a request as it goes through the handler pipeline.

GrpcChannel is different in that you specify the scheme + host, and then it only sends request to that address. Because of this, the channel has logic in it that knows whether it is https or http, and makes decisions based on that.

Maybe something could be done in Grpc.Net.Client. But GrpcChannel wasn't designed to work like this. It really wants to know what its scheme is when it's created, not when it is sending a gRPC call.

**Comment by DamianEdwards** [comment]
Can we integrate Service Discovery into the gRPC client in a different way, such that the address is fully resolved by the time the `GrpcChannel` is being created?

**Comment by DamianEdwards** [comment]
Next steps are to experiment with bringing back a gRPC resolver but this time for the "https+http" scheme (or whatever combination the user wants) and see how far we get with that approach.

**Comment by davidfowl** [comment]
Moving to p6, unclear if it meets the bar though

**Comment by DamianEdwards** [comment]
No we can move it out.

**Comment by DamianEdwards** [comment]
We should consider moving this to the backlog until we get user feedback that it's worth investigating.

**Comment by gabynevada** [comment]
What kind of feedback is needed for this? We're using grpc for some services and would love to see a solution for service discovery.

**Comment by DamianEdwards** [comment]
@gabynevada TBC, service discovery of the hostname/addresses does work right now, it's just the multi-scheme format fallback feature that doesn't work with gRPC, e.g. `https+http://my-service`. Do you have a specific need for that support?

**Comment by gabynevada** [comment]
@DamianEdwards Understood! We were using multi-scheme format but changed to a single scheme and it works fine. Don't have a need for multt-scheme for the moment, thanks!

**Comment by omarceloribeiro** [comment]
it not worked for me in .net 8 even using https://myservice

**Comment by DamianEdwards** [comment]
@omarceloribeiro are you getting any errors? Have you ensured that service discovery is configured for `HttpClient` correctly? The [Aspire Shop sample](https://github.com/dotnet/aspire-samples/tree/main/samples/AspireShop) includes a gRPC service (BasketService) and is targeting `net8.0`. Can you verify that you can run that sample successfully locally? If so, can you compare your code to what the sample is doing?

**Comment by omarceloribeiro** [comment]
the Aspire Shop is using AddGrpcServiceReference extension (https://github.com/dotnet/aspire-samples/blob/2bc9d5d26f0d7d2e0519d5a3d24ba5d96ab2feed/samples/AspireShop/AspireShop.ServiceDefaults/ServiceReferenceExtensions.cs#L93)
while I am calling the AddGrpcClient directly.

I will make a test using the extension to see if it works. I will also test to see if it works local or if the error is only when deploying to azure container apps.

thank you!

**Comment by mikeleigh1010** [comment]
@DamianEdwards interestingly coming against something similar

Current docs suggest (perhaps changed in .NET 9?) doing it slightly different to as is in the eshop example:

var isHttps = builder.Configuration["DOTNET_LAUNCH_PROFILE"] == "https";
builder.Services.AddGrpcClient<DiscountProtoService.DiscountProtoServiceClient>(options =>
    {
        // options.Address = new Uri($"{(isHttps ? "https" : "http")}://discountgrpcservice");
        options.Address = new Uri("https+http://discountgrpcservice");


Commented out way (like eshop) works fine, whereas the current docs way of being agnostic of http protocol does not work and returns

{
    "title": "InvalidOperationException",
    "status": 500,
    "detail": "No address resolver configured for the scheme 'https+http'.",
    "instance": "/basket",
    "traceId": "0HNBE1GV4T8GA:00000001"
}

**Comment by DamianEdwards** [comment]
@mikeleigh1010 yes this is exactly what this issue is about. The doc you're pointing at is using the `https+http` syntax for a standard `HttpClient` instance, not for a gRPC client. The gRPC client does not support the `https+http` syntax (this issue).

**Comment by AlgorithmsAreCool** [comment]
~This issue causes an additional allergic reaction to the way service discovery URLs are interpreted in a Kubernetes environment.~

~When in Kubernetes, the DSN SRV service discovery provider [uses the URI scheme as the portname](https://github.com/dotnet/aspire/blob/75fdcff28495bdd643f6323133a7d411df71ab70/src/Microsoft.Extensions.ServiceDiscovery.Dns/DnsSrvServiceEndpointProviderFactory.cs#L32) when looking up SRV record, but since we can't currently use non-standard schemes (`grpc://` in my case) the service discovery provider doesn't work correctly.~

After digging in the code more i have found that your can specify the port of a service by prefixingg the service discovery uri hostname with a `_<portname>.` segment.

e.g. if your desired portname is `abcd` and your service's name if `foo` you can specify the service discovery uri as `_abcd.foo` and it will work.

I believee the above linked comment in the code that indicates the scheme is to be used as the portname is incorrect.

But my above complaint is not actually valid.

**Comment by tjmoore** [comment]
Similar issue to SignalR resolution support #1356

**Comment by maddymontaquila** [comment]
This was fixed in PR #2895. gRPC clients now work correctly with Service Discovery scheme resolution syntax. Closing as fixed.

**Comment by DamianEdwards** [comment]
@maddymontaquila this wasn't fixed, just worked around in the sample app

**Comment by davidfowl** [comment]
Reopening after reviewing the recent bulk closure. The close comment appears to cite work that does not fully address this issue, so this should remain open for normal triage.
