### ISSUE TITLE
[WebToolsE2E] With no Docker or Podman installed, create Aspire Starter App with redis cache option and run, the error message calls out Docker not found but doesn't mention Podman

### ISSUE THREAD

**Issue by balachir** [dotnet/aspire#3190]
**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install Dev17.10.0 Preview 3.0 [main-34726.61] (Includes Aspire 8.0.0-preview.4.24156.9)
3. Install Aspire 8.0 P5 version 8.0.0-preview.5.24175.10 + Apply feeds
4. No Docker or Podman installed

**REPRO STEPS**
1. Create Aspire Starter App using command-line with redis cache option
    > dotnet new aspire-starter -o AspireStarterApp03withRedis --use-redis-cache

2. Navigate to AppHost folder and run the app
    > dotnet run

**ACTUAL**
You get the following error, which is expected. But the error is specific about Docker not being installed.

**Question**: Should the error be more general to indicate that either Docker or Podman needs to be installed.

![image](https://github.com/dotnet/aspire/assets/8246794/9c308f1a-f944-4ebf-8cef-52e66ec8997c)

**Notes**
With VS New Project dialog (NPD) too, the checkbox in NPD is specific about recommending Docker. See **AzDO 2004980**

![image](https://github.com/dotnet/aspire/assets/8246794/f9d0a2ca-8bd7-4462-8907-d043f195ebf5)

**Comment by balachir** [comment]
@DamianEdwards @davidfowl for scenarios like these, are we fine with recommending Docker or should the messaging be more general and recommend either Docker or Podman?

cc: @karolz-ms

**Comment by DamianEdwards** [comment]
It should be generalized to something like "a supported container runtime"

**Comment by timheuer** [comment]
> It should be generalized to something like "a supported container runtime"

David Pine just updated the doc point here about supported container runtime as well -- but I think the tool tip in VS doesn't allow hyperlink directly but we should put a readable aka.ms link (instead of FWLink)

**Comment by v-cazhang** [comment]
In AzDO bug 2004980, Vijay mentioned that:

This is in the templates:
https://github.com/dotnet/aspire/blob/ac2b068eb10096852a5e48d01615d9effa3331f2/src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json#L84-L85

**Comment by DamianEdwards** [comment]
Yep I'm fixing this

**Comment by DamianEdwards** [comment]
Fixed

**Comment by phenning** [comment]
Damian, you missed updating the templatestrings.en.json, so this still has the old value:

https://github.com/dotnet/aspire/blob/e0fe4a55fb734243ff2001900e97fd44511d1e12/src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.en.json#L7

**Comment by DamianEdwards** [comment]
Grrrr, I apologize but will take this opportunity to vent and say this is one of the areas that is too finicky with template authoring. We need to either, a) automate these steps, or b) make the build fail if the required steps aren't performed, /Cc @joperezr

I don't think this is a ship-blocker for preview. 5 but we should get this fixed for preview.6

**Comment by joperezr** [comment]
cc @radical regarding the above point from @DamianEdwards about adding a build test to detect this moving forward. This doesn't take precedence over the existing testing work you are doing, but let's just keep it on the radar so we get to it eventually.

**Comment by radical** [comment]
> cc @radical regarding the above point from @DamianEdwards about adding a build test to detect this moving forward. This doesn't take precedence over the existing testing work you are doing, but let's just keep it on the radar so we get to it eventually.

What would such a test do? Part of my current branch are tests that exercise some of the templates - IOW - `dotnet new .. dotnet run`. Is that the kind of thing expected or some other kind of template validation?

**Comment by DamianEdwards** [comment]
Ideally for this I think we'd have something as part of the templates project build, rather than a test. I guess it would verify that the keys in all the language `templatestrings.*.json` files match those in the `template.json` file, and that the values in the `templatestrings.en.json` file match those in the `template.json` file.

**Comment by phenning** [comment]
@baronfel @sayedihashimi is this something that could be baked into the template authoring validation tool?

**Comment by baronfel** [comment]
Created a tracking issue on our end for the request.

**Comment by balachir** [comment]
@DamianEdwards this seems to be fixed now with the latest Aspire P6 builds. Did you already make the additional change we discussed [here](https://github.com/dotnet/aspire/issues/3190#issuecomment-2030253227) and can we close this issue?
