### ISSUE TITLE
[WebToolsE2E][Aspire] After installing Aspire 8.1, the output of "cache" option in the Aspire dashboard shows few blanks lines when running Aspire Starter Application with Redis

### ISSUE THREAD

**Issue by vmykagapuz** [dotnet/aspire#4942]
**REGRESSION**
1. Worked in Aspire 8.0.0

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.11 Preview 5
3. Install Aspire 8.1
4. Install Docker Desktop

**REPRO STEPS**

1. Create Aspire Starter Application with redis, build solution and run 
2. Navigate to Aspire dashboard > Console Logs > cache

**ACTUAL**
The output in the "cache" option shows few blanks lines
![Aspire8 1](https://github.com/user-attachments/assets/1121c2d5-0b20-4745-a1fd-4662fe1f3bf9)

**EXPECTED**
The output in the "cache" option should not have blank lines
![Aspire8 0](https://github.com/user-attachments/assets/5f78f577-9fcc-45f5-ba5b-d9b663e928e1)

**Comment by balachir** [comment]
@mitchdenny one more issue that you may want to consider for 8.1. It's a minor issue but a regression compared to Aspire 8.0.

**Comment by karolz-ms** [comment]
These blank lines are coming from DCP; it is adding them to separate output of "startup log" commands. 

We could stop doing this altogether, or only emit separators when there is actual output from startup commands, or do something else. @leslierichardson95 Let's have a chat.

**Comment by mitchdenny** [comment]
Yeah so @balachir I think for now we consider this as by design. But I think we need to come up with a better log viewer experience when we consider multiple streams.

**Comment by vmykagapuz** [comment]
This issue is also found in the "messaging" and "sql" option under Console logs
![Sql](https://github.com/user-attachments/assets/66e54aae-f255-45c8-a797-3847a70d03d6)
![Messaging](https://github.com/user-attachments/assets/0f654bb7-a462-457f-81b7-444c21875059)

**Comment by leslierichardson95** [comment]
@karolz-ms I think we should only emit separators when the startup commands have actual output to display.  Timeline-wise, this feels less pressing so 8.2 as a priority would be cool with me.

**Comment by karolz-ms** [comment]
This should be fixed in DCP 0.6.0 or newer, which has been integrated into Aspire main this morning.

**Comment by vmykagapuz** [comment]
@karolz-ms I verified this issue and still encounter it in Aspire 8.1.1. May I know if this result is expected or not?
![BugVerified](https://github.com/user-attachments/assets/17e871fe-f539-41ce-a6ec-ce9627e1e1ff)

**Comment by karolz-ms** [comment]
@vmykagapuz this output is expected. Here is what is going on.

The first line comes from container creation step. The associated container image is presumably cached, so there is nothing about image download and the only output from the container creation is the ID of the new container (the long alphanumeric string).

Then there is a blank line separating the output of container creation step from container startup step.

Then there is the output of container startup. The startup is smooth, so the only output from container orchestrator is the container ID again.

Then the dashboard shows the output from actual running container. In the current implementation the dashboard does not visually separate the container creation and startup logs from running container logs, so the running container logs appear directly under container startup logs (no separator of any kind).

@leslierichardson95 please chime in (or open a new issue) if you think this could use some improvement.
