### ISSUE TITLE
[WebToolsE2E][Aspire] There are some warnings "[Deprecation] -ms-high-constrast is in the process of being deprecated" in the Edge website console pane when running the Aspire project

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#5279]
**REGRESSION INFO**: Work in Aspire 8.1.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.303
3. Install Aspire 8.1.1-preview.1.24412.4
4. Apply feed

**REPRO STEPS**
1. Open CMD, create an Aspire App using following commands:
```
dotnet new aspire -o AspireApp
cd AspireApp/AspireApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser.
`dotnet run`
3. Hit F12 and navigate to Console in the browser development tools.

**Note:**
1. This issue repro on Edge browser, it doesn't repro on Google Chrome and Firefox.
2. Manually refresh the page and the warning will disappear
3. This issue doesn't repro when running the normal project(eg: MVC/Razor/API project)

**ACTUAL**
There are some warnings in the Edge website console pane
![Screenshot 2024-08-13 152548](https://github.com/user-attachments/assets/dedbe407-9ec2-4a03-b426-585b73aa3666)

**EXPECTED**
The website console pane doesn't have any warnings when running the Aspire project

**Error Log**
`[Deprecation] -ms-high-constrast is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.`

**Comment by adamint** [comment]
Very low priority, adding to backlog

**Comment by JamesNK** [comment]
No longer an issue. I'm guessing the style was in FluentUI and was fixed there.

![Image](https://github.com/user-attachments/assets/079a0da8-b2bb-4abb-b488-04e27abf3562)

**Comment by Rita003** [comment]
@JamesNK Verify this issue still repro after installing the latest Aspire 9.1.0-preview.1.24569.4 / Aspire 8.2.2 in today's validation.
![Image](https://github.com/user-attachments/assets/bcada9a0-3007-4d73-ae57-e2e9165a02e1)

**Comment by Rita003** [comment]
Verify this issue fixed on the latest Aspire 9.1.0-preview.1.24570.3
