### ISSUE TITLE
[WebToolsE2E][Aspire] After selecting an instrument in the Metrics instrument group, the corresponding instrument list cannot be located.

### ISSUE THREAD

**Issue by Rita003** [dotnet/aspire#5596]
**REGRESSION INFO:** Work in Aspire 8.1.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 8.0.401
3. Install Aspire 8.2.0

**REPRO STEPS**
1. Open CMD, create an Aspire Starter App using following commands:
```
dotnet new aspire-starter -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser.
`dotnet run`
3. Click the "Metrics" option on the Aspire dashboard left, select a resource and click on any instrument group, select an instrument in the instrument group.

**ACTUAL**
After selecting an instrument in the instrument group, the corresponding instrument list cannot be located.
![Select](https://github.com/user-attachments/assets/6e5b8714-76b9-4816-a01b-aaa5ca09d387)

**EXPECTED**
It can locate the corresponding instrument list after selecting an instrument in the instrument group.
![Screenshot 2024-09-09 161722](https://github.com/user-attachments/assets/fa98c3fb-6913-4236-9c7c-f33c8dccf288)

**Comment by adamint** [comment]
Blocked on the open dashpages PR - #5750

**Comment by Rita003** [comment]
@adamint After installing the latest Aspire 9.1.0-preview.1.25069.2, selecting an instrument in the instrument group, the corresponding instrument list can be located. However, unlike the expected result in the bug, the instrument group is not located. I want to confirm whether this is expected?
For Aspire 9.1 dashboard results:
![Image](https://github.com/user-attachments/assets/a5fafeeb-db50-4941-90db-072eedf5635f)
Expected results for this bug:
![Image](https://github.com/user-attachments/assets/baeb059f-4730-4db8-82de-b5358a6d00a6)

**Comment by adamint** [comment]
>  unlike the expected result in the bug, the instrument group is not located. I want to confirm whether this is expected?

It is not expected. Still blocked on #5750

**Comment by JamesNK** [comment]
I retried this in 9.1 and I think this is fixed.

**Comment by Rita003** [comment]
> [@adamint](https://github.com/adamint) After installing the latest Aspire 9.1.0-preview.1.25069.2, selecting an instrument in the instrument group, the corresponding instrument list can be located. However, unlike the expected result in the bug, the instrument group is not located. I want to confirm whether this is expected? For Aspire 9.1 dashboard results: ![Image](https://github.com/user-attachments/assets/a5fafeeb-db50-4941-90db-072eedf5635f) 
Expected results for this bug: ![Image](https://github.com/user-attachments/assets/baeb059f-4730-4db8-82de-b5358a6d00a6)

@JamesNK Verify that this bug is still reproduced after installing the latest Aspire 9.1.0 and is the same as this comment. According to adamint's reply, it is not expected. Should we reopen this bug to track it?

**Comment by JamesNK** [comment]
The tree item selected is expected. The tree item scrolling into view if necessary isn’t expected to happen.
