### ISSUE TITLE
no runner found for execution type 'IDE' in .Net 9

### ISSUE THREAD

**Issue by huberttrueselftrueme** [dotnet/aspire#6657]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

After upgrade form .net 8 to .net 9 my aspire project is not able to run web applications. I get error no runner found for execution type 'IDE'

![Image](https://github.com/user-attachments/assets/49ac13b9-ca71-4ba9-9fd0-3c194ac6afed)

### Expected Behavior

I get the same behaviour when run existing projects, as well new projects or completely new solution form aspire templates.

### .NET Version info

.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100/

.NET workloads installed:
 [maui]
   Installation Source: SDK 9.0.100
   Manifest Version:    9.0.0/9.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100/microsoft.net.sdk.maui/9.0.0/WorkloadManifest.json
   Install Type:        FileBased

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: arm64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  9.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by Pertel** [comment]
Just experienced the same error, and found that it happens when i start the AppHost project from Rider, but works if I start it from CLI with `dotnet run`. So perhaps that will work as a temporary workaround, until more info is found.

**Comment by rafaelldi** [comment]
We also have an issue in the plugin repo https://github.com/JetBrains/aspire-plugin/issues/292. Unfortunately, I can't reproduce, so could you please provide more details?

**Comment by rafaelldi** [comment]
I fixed it in the 1.6.4 version of the plugin, please check it out.

**Comment by karolz-ms** [comment]
Fantastic, thanks @rafaelldi

**Comment by Shak-o** [comment]
I believe this issue is still not resolved. I have the Aspire plugin version 1.6.6 and encounter this error when trying to run the .NET 9 version of the Aspire AppHost. Visual Studio works just fine.  
![Image](https://github.com/user-attachments/assets/c99419a3-014f-48e7-a009-279abcba686a)
