### ISSUE TITLE
How to test only part of distributed application

### ISSUE THREAD

**Issue by lukedukeus** [dotnet/aspire#9803]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The aspire test host project shows how to test an entire distributed application at once, by doing something like:
```
 // Arrange
 var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.My_AppHost>();
 appHost.Services.ConfigureHttpClientDefaults(clientBuilder =>
 {
     clientBuilder.AddStandardResilienceHandler();
 });

 await using var app = await appHost.BuildAsync();
 var resourceNotificationService = app.Services.GetRequiredService<ResourceNotificationService>();
 await app.StartAsync();

 // Act
 var httpClient = app.CreateHttpClient("webfrontend");
 await resourceNotificationService.WaitForResourceAsync("webfrontend", KnownResourceStates.Running).WaitAsync(TimeSpan.FromSeconds(30));
 var response = await httpClient.GetAsync("/");

 // Assert
 Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
```

This works great, but in my distributed application, I have parts that I want to test with certain resources missing. For example, I might want to make sure that a website still works, even if the redis container is not present.

So, here is what I have tried:
```
 // Arrange
 var builder = DistributedApplicationTestingBuilder.Create();

 var databaseServer = builder.AddPostgres("Postgres");

 var centralDatabase = databaseServer.AddDatabase($"Database");

 var serverAPI = builder.AddProject<Projects.My_API>("API")
     .WithReference(centralDatabase)
     .WaitFor(centralDatabase);

 var client = builder.AddYarnApp($"Client", "../../Client")
     .WithReference(serverAPI)
     .WaitFor(serverAPI)
     .WithEnvironment("BROWSER", "none")
     .WithHttpsEndpoint(env: "VITE_PORT")
     .WithExternalHttpEndpoints();

 await using var app = await builder.BuildAsync();
 var resourceNotificationService = app.Services.GetRequiredService<ResourceNotificationService>();
 await app.StartAsync();

 // Act
 var httpClient = app.CreateHttpClient("webfrontend");
 await resourceNotificationService.WaitForResourceAsync(client.Resource.Name, KnownResourceStates.Running).WaitAsync(TimeSpan.FromSeconds(30));
 var response = await httpClient.GetAsync("/");

 // Assert
 Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
```

Unfortunatly, this results on this error on `DistributedApplicationTestingBuilder.Create()`:
```
System.InvalidOperationException: 'No application host assembly was found. Ensure that you have a project that references the 'Aspire.Hosting.AppHost' package and imports the 'Aspire.AppHost.Sdk' SDK.'
```

It looks to be the same error as #7808. My question is, am I using the API correctly, or is adding only specific resources to the builder not supported? I couldn't find any other examples doing things this way, but it makes sense that the API should work this way. I do not know enough about the internal workings of aspire to know or not.

**Comment by afscrome** [comment]
Can you share the csproj for your test project?  Does it reference the `Aspire.AppHost.Sdk` sdk and the `Aspire.Hosting.AppHost` package.  Should have something similar to:

```xml
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0" />

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
    <PackageReference Include="Aspire.Hosting.Testing" Version="9.3.0" />
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.2.0"  />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>
```

The issue you linked to was resolved in 9.3, with the fix beign to improve the error message to includ what is needed to make things work - `Ensure that you have a project that references the 'Aspire.Hosting.AppHost' package and imports the 'Aspire.AppHost.Sdk' SDK.'`.

**Comment by afscrome** [comment]
Alternatively if you only want to make slight modifications to your main app host, you can manipulate the resources before you build the DistributedApplicationTestingBuilder.  

You may need to jump through a few more hoops than simply removing the resources (e.g. removing environment variables, WaitFor and any other references to the removed resource), at which point it may be simpler to build what you need up from scratch.

```cs
    public async Task Test()
    {
        var builder = DistributedApplicationTestingBuilder.Create<aspire9_AppHost>();

        // Remove existing redis resource
        var redis = builder.Resources.OfType<RedisResource>().Single();
        builder.Resources.Remove(redis);

        // Add a new resource
        builder.AddContainer("nginx", "nginx");

        var app = builder.Build();

        await app.StartAsync();
    }
```

**Comment by lukedukeus** [comment]
> Can you share the csproj for your test project? Does it reference the `Aspire.AppHost.Sdk` sdk and the `Aspire.Hosting.AppHost` package. 

Here's what my `.csproj` looks like:
```
<Project Sdk="MSTest.Sdk/3.9.2">

  <PropertyGroup>
	<TargetFramework>net9.0</TargetFramework>
	<LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
	<TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
	<TestingExtensionsProfile>AllMicrosoft</TestingExtensionsProfile>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.0" />
    <PackageReference Include="Aspire.Hosting.Testing" Version="9.3.0" />
    <PackageReference Include="MSTest" Version="3.9.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Analyzers\ProductName.Shared.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\AppHost\ProductName.Hosting.AppHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Aspire.Hosting.ApplicationModel" />
    <Using Include="Aspire.Hosting.Testing" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.14.1" />
	<PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2" />
	<PackageReference Update="Microsoft.Testing.Extensions.CrashDump" Version="1.7.2" />
	<PackageReference Update="Microsoft.Testing.Extensions.HangDump" Version="1.7.2" />
	<PackageReference Update="Microsoft.Testing.Extensions.HotReload" Version="1.7.2" />
	<PackageReference Update="Microsoft.Testing.Extensions.Retry" Version="1.7.2" />
	<PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="1.7.2" />
	<PackageReference Update="MSTest.TestAdapter" Version="3.9.2" />
	<PackageReference Update="MSTest.TestFramework" Version="3.9.2" />
	<PackageReference Update="MSTest.Analyzers" Version="3.9.2">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

</Project>
```

also, the `ProductName.Hosting.AppHost.csproj` file also refrences `Aspire.Hosting.AppHost`, but I still get the same error with or without it. 

> The issue you linked to was resolved in 9.3, with the fix beign to improve the error message to includ what is needed to make things work - `Ensure that you have a project that references the 'Aspire.Hosting.AppHost' package and imports the 'Aspire.AppHost.Sdk' SDK.'`.

Thats why I wasn't sure if I was just using the API wrong, because it works fine when I do ` var appHost = await DistributedApplicationTestingBuilder.CreateAsync<Projects.My_AppHost>();`

**Comment by afscrome** [comment]
Your test project is missing the SDK reference.  Add this in to your test project.

```xml
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.0" />
```

**Comment by lukedukeus** [comment]
As soon as I add that, it changes the icon from the test icon in solution explorer to the aspire icon:

![Image](https://github.com/user-attachments/assets/57dfb5ad-7923-4d89-b41c-c7abfd6d5527)

And it gives errors about not being able to find the project:
```
1>C:\Users\vanzw\OneDrive\Documents\Development\ProductName\src\Hosting\Tests\WebTests.cs(17,38,17,49): error CS1061: 'IDistributedApplicationTestingBuilder' does not contain a definition for 'AddPostgres' and no accessible extension method 'AddPostgres' accepting a first argument of type 'IDistributedApplicationTestingBuilder' could be found (are you missing a using directive or an assembly reference?)
1>C:\Users\vanzw\OneDrive\Documents\Development\ProductName\src\Hosting\Tests\WebTests.cs(21,53,21,70): error CS0234: The type or namespace name 'ProductName_Server_API' does not exist in the namespace 'Projects' (are you missing an assembly reference?)
1>C:\Users\vanzw\OneDrive\Documents\Development\ProductName\src\Hosting\Tests\WebTests.cs(25,30,25,40): error CS1061: 'IDistributedApplicationTestingBuilder' does not contain a definition for 'AddYarnApp' and no accessible extension method 'AddYarnApp' accepting a first argument of type 'IDistributedApplicationTestingBuilder' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by lukedukeus** [comment]
Nevermind, the issue is fixed if I add the project refrence again. I found I have to add it twice, once as an aspire resource and once not as an aspire resource:
```
	<ProjectReference Include="..\..\Server\API\ProductName.Server.API.csproj" />
	<ProjectReference Include="..\..\Server\API\ProductName.Server.API.csproj" IsAspireProjectResource="false" />
```
